language: d

matrix:
  include:
    - d: dmd
      env:
        - COVERAGE=true
        - secure: eCT5571JwRgcPq3PqOlBF7bgyJO+lhFQJyjn19ZW2xUTvoQq5Rxfjplgh2YgDD7INzaJ4vzFLVH/07+iWrQujYKjNyLTHumACPddLKBYRIAHC9glGyDkyAZ7vl53+f8Xfy0qNLcEPs56jsWRVS3QuSN1WuX1IAvQgsDcKKtYi7s=
    - d: ldc
    - d: gdc

script: ./travis.sh
